import { useCallback, useEffect, useSyncExternalStore } from "react";

export const LANGUAGE_OPTIONS = ["en", "zh-CN"] as const;
export type Language = (typeof LANGUAGE_OPTIONS)[number];

const MESSAGES = {
  en: {
    search: "Search",
    projects: "Projects",
    addProject: "Add project",
    newThread: "New thread",
    groupedProjects: "projects",
    sidebarOptions: "Sidebar options",
    sortProjects: "Sort projects",
    sortThreads: "Sort threads",
    visibleThreads: "Visible threads",
    visibleThreadCount: "Visible thread count",
    decreaseVisibleThreadCount: "Decrease visible thread count",
    increaseVisibleThreadCount: "Increase visible thread count",
    groupProjects: "Group projects",
    sendMessage: "Send message",
    plan: "Plan",
    build: "Build",
    runtimeMode: "Runtime mode",
    hideSidebar: "Hide {label} sidebar",
    showSidebar: "Show {label} sidebar",
    planModeHint: "Plan mode — click to return to normal build mode",
    buildModeHint: "Default mode — click to enter plan mode",
    resolveApproval: "Resolve this approval request to continue",
    writeCustomAnswer: "Write custom answer",
    expandComposer: "Expand composer",
    typeOwnAnswer: "Type your own answer, or leave this blank to use the selected option",
    refinePlan: "Add feedback to refine the plan, or leave this blank to implement it",
    followUpOrAttach: "Ask for follow-up changes or attach images",
    composerPlaceholder: "Ask anything, @tag files/folders, $use skills, or / for commands",
    attachAfterPlan: "Attach images after answering plan questions.",
    unsupportedImage: "Unsupported file type for '{name}'. Please attach image files only.",
    imageTooLarge: "'{name}' exceeds the {limit} attachment limit.",
    tooManyImages: "You can attach up to {count} images per message.",
    somethingWentWrong: "Something went wrong.",
    tryAgain: "Try again",
    reloadApp: "Reload app",
    showErrorDetails: "Show error details",
    hideErrorDetails: "Hide error details",
    commandPalette: "Command palette",
    back: "Back",
    continue: "Continue",
    working: "Working",
    cloning: "Cloning",
    repository: "Repository",
    navigate: "Navigate",
    select: "Select",
    close: "Close",
    openIn: "Open in {name}",
    newThreadIn: "New thread in…",
    newThreadInProject: "New thread in {project}",
    openWslFolder: "Open WSL folder",
    openSettings: "Open settings",
    unableToBrowseProjects: "Unable to browse projects",
    noEnvironmentAvailable: "No environment is available.",
    enterGitUrl: "Enter a Git clone URL and press Enter to continue.",
    enterRepositoryPath: "Enter a repository path and press Enter to look it up.",
    chooseCloneDestination: "Choose a destination path and press Enter to clone.",
    relativePathNeedsProject: "Relative paths require an active project.",
    createFolderAndAddProject: "Press Enter to create this folder and add it as a project.",
    searchCommandsProjectsThreads: "Search commands, projects, and threads…",
    enterProjectPath: "Enter project path (e.g. ~/projects/my-app)",
    searchPlaceholder: "Search…",
    enterPath: "Enter path (e.g. ~/projects/my-app)",
    selectCloneDestination: "Select where to clone",
    createAndClone: "Create & Clone",
    clone: "Clone",
    createAndAdd: "Create & Add",
    add: "Add",
    lookup: "Lookup",
    submitting: "Submitting…",
    submit: "Submit",
    next: "Next",
    nextQuestion: "Next question",
    submitAnswers: "Submit answers",
    submitAnswer: "Submit answer",
    previousQuestion: "Previous question",
    previous: "Previous",
    stopGeneration: "Stop generation",
    sending: "Sending…",
    refine: "Refine",
    implement: "Implement",
    implementationActions: "Implementation actions",
    implementInNewThread: "Implement in a new thread",
    environmentDisconnected: "Environment disconnected",
    connecting: "Connecting",
    preparingWorktreeShort: "Preparing worktree",
    cancelTurn: "Cancel turn",
    decline: "Decline",
    alwaysAllowSession: "Always allow this session",
    approveOnce: "Approve once",
    removeReviewComment: "Remove comment on {label}",
    noActiveThread: "No active thread",
    pickThread: "Pick a thread to continue",
    pickThreadDescription: "Select an existing thread or create a new one to get started.",
    planActions: "Plan actions",
    copied: "Copied!",
    copyToClipboard: "Copy to clipboard",
    downloadMarkdown: "Download as markdown",
    saveToWorkspace: "Save to workspace",
    planSaved: "Plan saved",
    couldNotSavePlan: "Could not save plan",
    unexpectedError: "An unexpected error occurred.",
    steps: "Steps",
    fullPlan: "Full plan",
    browser: "Browser",
    terminal: "Terminal",
    files: "Files",
    diff: "Diff",
    openSurface: "Open a surface",
    chooseRightPanel: "Choose what to show in the right panel.",
    openLocalApp: "Open a local app or URL.",
    startShell: "Start a shell in this workspace.",
    browseWorkspaceFiles: "Browse and read workspace files.",
    reviewThreadChanges: "Review changes in this thread.",
    browserDesktopOnly: "Browser previews are only available in the T3 Code desktop app.",
    filesNeedProject: "Files are only available when a project is open.",
    diffNeedsGit: "Diff is only available for server threads in Git repositories.",
    copyPath: "Copy path",
    closeOthers: "Close others",
    closeToRight: "Close to the right",
    closeAll: "Close all",
    closeSurface: "Close {title}",
    addPanelSurface: "Add panel surface",
    indexing: "Indexing…",
    fileCount: "{count} files",
    partial: "partial",
    searchWorkspaceFiles: "Search workspace files",
    refreshWorkspaceFiles: "Refresh workspace files",
    projectFiles: "{project} files",
    unableOpenFileBrowser: "Unable to open file in browser",
    showMarkdownSource: "Show markdown source",
    showRenderedMarkdown: "Show rendered markdown",
    openFilePreview: "Open file in preview browser",
    hideFileExplorer: "Hide file explorer",
    showFileExplorer: "Show file explorer",
    previewLimited: "Preview limited to the first 1 MB of a {count} byte file.",
    publishRepository: "Publish repository…",
    detachedHeadWarning:
      "Detached HEAD: create and check out a branch to enable push and pull request actions.",
    behindUpstreamWarning: "Behind upstream. Pull or rebase first.",
    gitActions: "Git actions",
    gitActionOptions: "Git action options",
    branch: "Branch",
    detachedHead: "(detached HEAD)",
    defaultBranchWarning: "Warning: default branch",
    filesSelected: "({selected} of {total})",
    done: "Done",
    edit: "Edit",
    none: "none",
    excluded: "Excluded",
    commitMessageOptional: "Commit message (optional)",
    autoGenerateCommitMessage: "Leave empty to auto-generate",
    commitOnNewBranch: "Commit on new branch",
    commit: "Commit",
    runOnDefaultBranch: "Run action on default branch?",
    abort: "Abort",
    cancel: "Cancel",
    timeFormat: "Time format",
    systemClockPreference: "System default follows your browser or OS clock preference.",
    wordWrap: "Word wrap",
    wordWrapDescription:
      "Wrap long lines in code blocks, tables, diffs, and file previews by default.",
    hideWhitespaceChanges: "Hide whitespace changes",
    hideWhitespaceDescription:
      "Set whether the diff panel ignores whitespace-only edits by default.",
    assistantOutput: "Assistant output",
    assistantOutputDescription: "Show token-by-token output while a response is in progress.",
    providerUpdateChecks: "Provider update checks",
    providerUpdateDescription: "Check installed provider CLIs for newer available versions.",
    autoOpenTaskPanel: "Auto-open task panel",
    autoOpenTaskDescription:
      "Open the right-side plan and task panel automatically when steps appear.",
    newThreads: "New threads",
    newThreadsDescription: "Pick the default workspace mode for newly created draft threads.",
    local: "Local",
    newWorktree: "New worktree",
    archiveConfirmation: "Archive confirmation",
    archiveConfirmationDescription:
      "Require a second click on the inline archive action before a thread is archived.",
    deleteConfirmation: "Delete confirmation",
    deleteConfirmationDescription: "Ask before deleting a thread and its chat history.",
    keybindings: "Keybindings",
    bindingCount: "{count} bindings",
    addKeybinding: "Add keybinding",
    openKeybindingsFile: "Open keybindings.json",
    browserShortcutWarning:
      "Some shortcuts may be claimed by the browser before T3 Code sees them. Use the desktop app for better keybinding support.",
    command: "Command",
    keybinding: "Keybinding",
    when: "When",
    status: "Status",
    noMatchingKeybindings: "No keybindings match your search.",
    liveProcesses: "Live Processes",
    refreshProcessDiagnostics: "Refresh process diagnostics",
    childProcesses: "Child Processes",
    memory: "Memory",
    serverPid: "Server PID",
    loadingLiveProcesses: "Loading live processes…",
    noLiveProcesses: "No live descendant processes found.",
    resourceHistory: "Resource History",
    refreshResourceHistory: "Refresh resource history",
    collectingResourceSamples: "Collecting process resource samples…",
    noResourceSamples: "No process resource samples found for this window.",
    traceDiagnostics: "Trace Diagnostics",
    openLogsFolder: "Open logs folder",
    refreshTraceDiagnostics: "Refresh trace diagnostics",
    failures: "Failures",
    slowSpans: "Slow Spans",
    parseErrors: "Parse Errors",
    workingTree: "Working tree",
    branchChanges: "Branch changes",
    latestTurn: "Latest turn",
    searchRefs: "Search refs…",
    stackedDiff: "Stacked diff view",
    splitDiff: "Split diff view",
    disableLineWrapping: "Disable line wrapping",
    enableLineWrapping: "Enable line wrapping",
    showWhitespaceChanges: "Show whitespace changes",
    loadingDiff: "Loading diff…",
    noNetChanges: "No net changes in this selection.",
    noPatchAvailable: "No patch available for this selection.",
    expandDiff: "Expand diff",
    collapseDiff: "Collapse diff",
    navigation: "Navigation",
    browserBack: "Back",
    forward: "Forward",
    refresh: "Refresh",
    stop: "Stop",
    searchOrEnterUrl: "Search or enter URL",
    openInSystemBrowser: "Open in system browser",
    cancelAnnotation: "Cancel annotation",
    cancelAnnotationShortcut: "Cancel annotation (Esc)",
    annotatePreview: "Annotate preview",
    annotateElements: "Annotate elements, regions, and drawings",
    stopRecording: "Stop recording",
    captureScreenshot: "Capture screenshot",
    screenshotOrRecord: "Screenshot · Shift-click to record",
    siteUnreachable: "This site can’t be reached",
    previewConnectionIssue: "{host}: {reason}.",
    try: "Try:",
    checkConnection: "Checking your connection",
    confirmDevServer: "Confirming the dev server is running",
    checkProxyFirewall: "Checking the proxy and the firewall",
    details: "Details",
    hideDetails: "Hide details",
    reload: "Reload",
    noTerminalSessions: "No terminal sessions for this thread yet.",
    newTerminal: "New terminal",
    closeTerminal: "Close terminal",
    splitTerminalHorizontally: "Split terminal horizontally",
    splitTerminalVertically: "Split terminal vertically",
    terminalSplitLimit: "{action} (max {count} per group)",
    terminalWithShortcut: "{action} ({shortcut})",
    terminalGroup: "Group {count}",
    projectScripts: "Project scripts",
    runAction: "Run {name}",
    scriptActions: "Script actions",
    addAction: "Add action",
    editAction: "Edit {name}",
    setup: "setup",
    editActionTitle: "Edit action",
    addActionTitle: "Add action",
    actionsDescription:
      "Actions are project-scoped commands you can run from the top bar or keybindings.",
    name: "Name",
    chooseIcon: "Choose icon",
    pressShortcut: "Press shortcut",
    pressShortcutHelp: "Press a shortcut. Use Backspace to clear.",
    previewUrlOptional: "Preview URL (optional)",
    openPreviewWhenRun: "Open this URL in the in-app preview when this action runs.",
    runOnWorktreeCreate: "Run automatically on worktree creation",
    autoOpenPreview: "Open preview automatically when this action runs",
    saveChanges: "Save changes",
    saveAction: "Save action",
    deleteAction: "Delete action",
    deleteActionConfirm: "Delete action “{name}”?",
    cannotUndo: "This action cannot be undone.",
    nameRequired: "Name is required.",
    commandRequired: "Command is required.",
    failedToSaveAction: "Failed to save action.",
    openInEditor: "Open in editor",
    open: "Open",
    openFileInPreferredEditor: "Open file in preferred editor",
    chooseEditor: "Choose editor",
    noInstalledEditors: "No installed editors found",
    addProviderInstance: "Add provider instance",
    providers: "Providers",
    refreshProviderStatus: "Refresh provider status",
    providerSettings: "{name} provider settings",
    addProviderDescription:
      "Configure an additional provider instance — for example, a second Codex install pointed at a different workspace.",
    driver: "Driver",
    identity: "Identity",
    config: "Configuration",
    step: "Step {count}",
    comingSoon: "Coming soon",
    label: "Label",
    providerLabelHint: "Shown in the provider list. Optional.",
    instanceId: "Instance ID",
    instanceIdHint: "Routing key used by threads and sessions. Letters, digits, '-', or '_'.",
    accentColor: "Accent color",
    providerAccentColor: "Provider instance accent color",
    useAccent: "Use {color} accent",
    clear: "Clear",
    accentColorHint: "Optional marker shown in the picker.",
    noProviderConfiguration:
      "This driver has no required configuration. You can add the instance now.",
    addInstance: "Add instance",
    models: "Models",
    modelsAvailable: "{count} models available.",
    enterModelSlug: "Enter a model slug.",
    modelBuiltIn: "That model is already built in.",
    modelSlugTooLong: "Model slugs must be {count} characters or less.",
    customModelExists: "That custom model is already saved.",
    fastMode: "Fast mode",
    thinking: "Thinking",
    reasoning: "Reasoning",
    modelDetails: "Details for {name}",
    hidden: "hidden",
    custom: "custom",
    removeFromFavorites: "Remove {name} from favorites",
    addToFavorites: "Add {name} to favorites",
    moveUp: "Move {name} up",
    moveDown: "Move {name} down",
    showModel: "Show {name}",
    hideModel: "Hide {name}",
    showInPicker: "Show in picker",
    hideFromPicker: "Hide from picker",
    removeCustomModel: "Remove custom model",
    removeModel: "Remove {name}",
    workspace: "Workspace",
    currentWorktree: "Current worktree",
    currentCheckout: "Current checkout",
    worktree: "Worktree",
    localCheckout: "Local checkout",
    runOn: "Run on",
    checkoutReference: "Check out {name}",
    checkoutReferenceDescription:
      "Resolve a {provider} {name}, then create the draft thread in the main repository or a dedicated worktree.",
    referenceInputHint: "Paste a {name} URL, checkout command, or enter 123 / #123.",
    referenceInputInvalid: "Use a {name} URL, checkout command, 123, or #123.",
    failedToPrepareThread: "Failed to prepare {name} thread.",
    referencePlaceholder: "{name} URL, checkout command, or #42",
    branchTo: "{head} to {base}",
    resolvingReference: "Resolving {name}…",
    preparingLocal: "Preparing local…",
    preparingWorktree: "Preparing worktree…",
    worktreeLocation: "Worktree: {path}",
    worktreeLocationBranch: "Worktree: {path} ({branch})",
    terminalProcessRunning: "Terminal process running",
    remote: "Remote",
    toggleMainSidebar: "Toggle main sidebar",
    toggleMainSidebarShortcut: "Toggle main sidebar ({shortcut})",
    deleteProviderInstance: "Delete provider instance {id}",
    deleteInstance: "Delete instance",
    authenticatedAs: "Authenticated as",
    email: "Email",
    updateAvailable: "Update available",
    updating: "Updating",
    updateNow: "Update now",
    updateManually: "or, update manually using",
    copyUpdateCommand: "Copy update command",
    copyCommand: "Copy command",
    toggleDetails: "Toggle {name} details",
    enableProvider: "Enable {name}",
    displayName: "Display name",
    instanceLabel: "Instance label",
    displayNameHint: "Optional label shown in the provider list.",
    providerAccentDescription: "Used to distinguish this instance in picker rails and model lists.",
    environmentVariables: "Environment variables",
    addEnvironmentVariable: "Add environment variable",
    environmentVariablesHint:
      "Add variables to pass API keys, base URLs, or other per-instance CLI settings.",
    variable: "Variable",
    value: "Value",
    sensitive: "Sensitive",
    options: "Options",
    environmentVariableName: "Environment variable name {count}",
    environmentVariableValue: "Environment variable value {count}",
    storedSecretHint: "Stored secret — enter a new value to replace",
    markEnvironmentVariableSensitive: "Mark environment variable {name} as sensitive",
    removeEnvironmentVariable: "Remove environment variable {name}",
    sensitiveValueStorage:
      "Sensitive values are stored separately and are not returned to the app after saving.",
    customHexAccentColor: "Custom hex accent color",
    chooseCustomAccentColor: "Choose custom accent color for {name}",
    clearAccentColor: "Clear accent color for {name}",
    binaryPath: "Binary path",
    binaryPathDescription: "Path to the provider binary used by this instance.",
    homePath: "Home path",
    homePathDescription: "Custom home and configuration directory for this instance.",
    shadowHomePath: "Shadow home path",
    shadowHomePathDescription:
      "Account-specific home that keeps authentication separate while sharing configuration state.",
    launchArguments: "Launch arguments",
    launchArgumentsDescription: "Additional CLI arguments passed when a session starts.",
    apiEndpoint: "API endpoint",
    apiEndpointDescription: "Override the API endpoint for this instance.",
    serverUrl: "Server URL",
    serverUrlDescription: "Leave blank to let T3 Code start the server when needed.",
    serverPassword: "Server password",
    serverPasswordDescription: "Stored in plain text on disk.",
    toggleAccountEmailVisibility: "Toggle account email visibility",
    revealEmail: "Click to reveal email",
    hideEmail: "Click to hide email",
    updateCommandCopied: "{name} update command copied",
    updateCommandCopiedDescription: "Run it in a terminal when you are ready to update.",
    couldNotCopyUpdateCommand: "Could not copy {name} update command",
    instanceIdRequired: "Instance ID is required.",
    instanceIdTooLong: "Instance ID must be 64 characters or fewer.",
    instanceIdInvalid:
      "Instance ID must start with a letter and use only letters, digits, '-', or '_'.",
    instanceIdExists: "An instance named '{id}' already exists.",
    providerInstanceAdded: "Provider instance added",
    providerInstanceAddedDescription: "{name} instance '{id}' was added.",
    couldNotAddProviderInstance: "Could not add provider instance",
    updateFailed: "Update failed.",
    checkingProviderStatus: "Checking provider status",
    waitingProviderStatus:
      "Waiting for the server to report installation and authentication details.",
    disabled: "Disabled",
    providerDisabledDescription:
      "This provider is installed but disabled for new sessions in T3 Code.",
    notFound: "Not found",
    cliNotDetected: "CLI not detected on PATH.",
    authenticated: "Authenticated",
    authenticatedWithLabel: "Authenticated · {label}",
    notAuthenticated: "Not authenticated",
    needsAttention: "Needs attention",
    providerWarningDescription:
      "The provider is installed, but the server could not fully verify it.",
    providerUnavailableDescription: "The provider failed its startup checks.",
    available: "Available",
    providerAvailableDescription: "Installed and ready, but authentication could not be verified.",
    updateAvailableVersion: "Update available: install {version}.",
    updateAvailableLatest: "Update available: install the latest provider version.",
    toggleTask: "Toggle task",
    openInIntegratedBrowser: "Open in integrated browser",
    collapseTableCells: "Collapse table cells",
    expandTableCells: "Expand table cells",
    copyTable: "Copy table",
    copyAsMarkdown: "Copy as Markdown",
    copyAsCsv: "Copy as CSV",
    language: "Language: {language}",
    disableLineWrap: "Disable line wrap",
    wrapLines: "Wrap lines",
    copyCode: "Copy code",
    unableToOpenFile: "Unable to open file",
    unableToOpenFileInBrowser: "Unable to open file in browser",
    errorOccurred: "An error occurred.",
    failedToCopy: "Failed to copy {name}",
    clipboardUnavailable: "Clipboard API unavailable.",
    copiedValue: "{name} copied",
    copyRelativePath: "Copy relative path",
    copyFullPath: "Copy full path",
    relativePath: "Relative path",
    fullPath: "Full path",
    resetToDefault: "Reset to default",
    resetSettingToDefault: "Reset {name} to default",
    revoking: "Revoking…",
    revokeOthers: "Revoke others",
    createLink: "Create link",
    createPairingLink: "Create pairing link",
    pairingLinkDescription:
      "Generate a one-time link that another device can use to pair with this backend as an authorized client.",
    clientLabelOptional: "Client label (optional)",
    permissions: "Permissions",
    limitPairedClient: "Limit what the paired client can do.",
    readOnly: "Read only",
    selectPermission: "Select at least one permission.",
    failedCreatePairingUrl: "Failed to create pairing URL.",
    couldNotCreatePairingUrl: "Could not create pairing URL",
    thisDevice: "This device",
    clientScopes: "Client scopes",
    revoke: "Revoke",
    host: "Host",
    pairingCode: "Pairing code",
    pastePairingUrlHint: "Paste a full pairing URL here to fill both fields automatically.",
    addEnvironment: "Add environment",
    addingEnvironment: "Adding…",
    sshHostOrAlias: "SSH host or alias",
    searchHostsOrType: "Search hosts or type devbox",
    username: "Username",
    port: "Port",
    suggestedHosts: "Suggested hosts",
    suggestedHostsDescription: "From SSH config and known hosts",
    noNewSshHosts: "No new SSH hosts were discovered.",
    remoteEnvironments: "Remote environments",
    addEnvironmentTitle: "Add environment",
    addEnvironmentDescription: "Pair another environment to this client.",
    remoteLink: "Remote link",
    remoteLinkDescription: "Enter a backend host and pairing code.",
    sshConnectionDescription: "Use local SSH config, agent, and tunnels for the backend.",
    pairingLink: "Pairing link",
    pairingUrls: "Pairing URLs",
    hostedAppLink: "Hosted app link",
    tokenOnly: "Token only",
    showQrCode: "Show QR code",
    scanPairingLink: "Pairing link — scan to open on another device",
    pairingLinkScopes: "Pairing link scopes",
    copyTokenPairingHint:
      "Copy the token and pair from another client using this backend's reachable host.",
    copyPairingUrlFor: "Copy pairing URL for: {endpoint}",
    chooseEndpointToCopy: "Choose endpoint to copy",
    showLink: "Show link",
    showCode: "Show code",
    hostedAppPairingLink: "Hosted app pairing link",
    pairingCodeTitle: "Pairing code",
    copyUnavailableCodeHint:
      "Clipboard copy is unavailable here. Manually copy this code into another client.",
    scopeCountOne: "{count} scope",
    scopeCountOther: "{count} scopes",
    connectedFor: "Connected for {duration}",
    connected: "Connected",
    lastConnectedAt: "Last connected at {time}",
    notConnectedYet: "Not connected yet.",
    traceIdCopied: "Trace ID copied",
    couldNotCopyTraceId: "Could not copy trace ID",
    versionDrift: "Version drift: client {client}, server {server}.",
    copyTraceId: "Copy trace ID",
    managedAbove: "Managed above",
    wslManagedHint:
      "The WSL backend is managed by the WSL setting above — turn it on or off there.",
    disconnecting: "Disconnecting…",
    disconnect: "Disconnect",
    connect: "Connect",
    noSavedRemoteEnvironments: "No saved remote environments",
    noSavedRemoteEnvironmentsCloud:
      "Click “Add environment” to pair another environment, or connect one from T3 Connect.",
    noSavedRemoteEnvironmentsLocal: "Click “Add environment” to pair another environment.",
    hide: "Hide",
    reachableAt: "Reachable at ",
    networkAccess: "Network access",
    enableNetworkAccess: "Enable network access",
    exposedOnAllInterfaces: "Exposed on all interfaces.",
    exposedOnAllInterfacesWithHost: "Exposed on all interfaces. Pairing links use {host}.",
    limitedToThisMachine: "Limited to this machine.",
    loading: "Loading…",
    remoteAccessConfigured:
      "This backend is already configured for remote access. Network exposure changes must be made where the server is launched.",
    localOnlyAccess:
      "This backend is only reachable on this machine. Restart it with a non-loopback host to enable remote pairing.",
    tailscaleHttpsDescription:
      "Use Tailscale Serve to expose this backend through a MagicDNS HTTPS URL.",
    tailscaleStartDescription: "Start Tailscale to set up HTTPS access through MagicDNS.",
    enableTailscaleHttps: "Enable Tailscale HTTPS",
    enableNetworkAccessConfirm: "Enable network access?",
    disableNetworkAccessConfirm: "Disable network access?",
    enableNetworkAccessDescription:
      "T3 Code will restart to expose this environment over the network.",
    disableNetworkAccessDescription:
      "T3 Code will restart and limit this environment back to this machine.",
    restarting: "Restarting…",
    restartAndEnable: "Restart and enable",
    restartAndDisable: "Restart and disable",
    disableTailscaleHttpsConfirm: "Disable Tailscale HTTPS?",
    disableTailscaleHttpsDescription:
      "T3 Code will restart the local backend without Tailscale Serve.",
    setupTailscaleHttpsConfirm: "Set up Tailscale HTTPS?",
    setupTailscaleHttpsDescription:
      "T3 Code will restart the local backend with Tailscale Serve enabled and ask Tailscale to proxy HTTPS traffic to this backend.",
    httpsPort: "HTTPS port",
    enterHttpsPortRange: "Enter a port from 1 to 65535.",
    httpsEndpoint: "HTTPS endpoint",
    pendingMagicDnsEndpoint: "Pending MagicDNS endpoint",
    enable: "Enable",
    wslBackend: "WSL backend",
    couldNotLoadWslBackend: "Couldn't load the WSL backend state.",
    retrying: "Retrying…",
    retry: "Retry",
    wslUnavailableDescription:
      "WSL is no longer available, so the Windows backend is running instead. Switch off the WSL backend to clear this preference.",
    switchToWindows: "Switch to Windows",
    off: "Off",
    defaultDistro: "Default distro",
    wslBackendDescription:
      "Run a second backend inside a WSL distro alongside the Windows one. Pick a distro to start it; pick Off to stop it. Projects opened against the WSL backend live on the Linux side; Windows projects stay where they are.",
    wslBackendStartFailed: "WSL backend couldn't start: {error}",
    defaultMarker: " (default)",
    wslOnly: "WSL only",
    wslOnlyDescription:
      "Stop the Windows backend and run only the WSL backend. Useful if you develop entirely inside WSL and don't want a second backend process. T3 Code restarts when you change this.",
    runWslOnly: "Run WSL only",
    turnOffWslAndSwitchWindows: "Turn off WSL and switch back to Windows?",
    disableWslBackend: "Disable WSL backend?",
    switchWslDistro: "Switch WSL distro?",
    startWslBackend: "Start the WSL backend",
    runOnlyWslBackend: "Run only the WSL backend?",
    reenableWindowsBackend: "Re-enable the Windows backend?",
    wslSwitchWindowsDescription:
      "T3 Code will restart on the Windows backend. Threads and projects opened against WSL stay safe inside the distro and become available again when you re-enable WSL.",
    wslDisableDescription:
      "The WSL backend will stop. Threads and projects opened against WSL stay safe inside the distro, but they'll be unavailable in T3 Code until you re-enable WSL.",
    wslSwitchDistroDescription:
      "T3 Code will restart the WSL backend on the new distro. Sessions still running on the current distro will be interrupted.",
    wslStartDescription:
      "Run the WSL backend alongside the Windows one, or stop the Windows backend and use only WSL? You can change this later from Settings.",
    wslOnlyDescriptionConfirm:
      "T3 Code will restart and start only the WSL backend. Your Windows-side projects won't be accessible until you turn this off again.",
    wslReenableWindowsDescription:
      "T3 Code will restart and bring the Windows backend back up alongside WSL.",
    applying: "Applying…",
    useOnlyWsl: "Use only WSL",
    runBothBackends: "Run both backends",
    disableWsl: "Disable WSL",
    switchDistro: "Switch distro",
    enableT3Connect: "Enable T3 Connect",
    signInT3Connect: "Sign in to T3 Connect to manage this environment.",
    noT3ConnectPermission: "Your session does not have permission to manage T3 Connect access.",
    t3ConnectLinked: "T3 Connect linked",
    t3ConnectTunnelDisabled: "T3 Connect tunnel disabled",
    t3ConnectUnlinked: "T3 Connect unlinked",
    t3ConnectAvailable: "This environment is available through T3 Connect.",
    t3ConnectTunnelRemoved: "The managed tunnel was removed. Agent activity publishing stays on.",
    t3ConnectUnavailable: "This environment is no longer available through T3 Connect.",
    agentActivityEnabled: "Agent activity enabled",
    agentActivityDisabled: "Agent activity disabled",
    agentActivityEnabledDescription:
      "This environment publishes agent activity to your mobile clients.",
    agentActivityDisabledDescription: "This environment will stop publishing agent activity.",
    t3ConnectAvailableDevices:
      "This environment is available to your other devices through T3 Connect.",
    t3ConnectMakeAvailable:
      "Make this environment available to your other devices through T3 Connect.",
    publishAgentActivity: "Publish agent activity",
    publishAgentActivityDescription:
      "Send activity from this environment to your mobile clients for push notifications and Live Activities. Works without a T3 Connect tunnel.",
    publishAgentActivityAria: "Publish agent activity to mobile clients",
    failedNetworkExposure: "Failed to update network exposure.",
    couldNotUpdateNetworkAccess: "Could not update network access",
    failedConfigureTailscale: "Failed to configure Tailscale HTTPS.",
    couldNotSetupTailscale: "Could not set up Tailscale HTTPS",
    failedDisableTailscale: "Failed to disable Tailscale HTTPS.",
    couldNotDisableTailscale: "Could not disable Tailscale HTTPS",
    failedRevokePairingLink: "Failed to revoke pairing link.",
    couldNotRevokePairingLink: "Could not revoke pairing link",
    failedRevokeClientAccess: "Failed to revoke client access.",
    couldNotRevokeClientAccess: "Could not revoke client access",
    revokedOtherClient: "Revoked 1 other client",
    revokedOtherClients: "Revoked {count} clients",
    revokedOtherClientsDescription:
      "Other paired clients will need a new pairing link before reconnecting.",
    failedRevokeOtherClients: "Failed to revoke other clients.",
    couldNotRevokeOtherClients: "Could not revoke other clients",
    environmentConnected: "Environment connected",
    environmentReconnected: "Environment reconnected",
    sshTunnelReady: "{name} is ready over an SSH-managed tunnel.",
    failedAddBackend: "Failed to add backend.",
    couldNotAddBackend: "Could not add backend",
    backendAdded: "Backend added",
    backendAddedDescription: "The environment is saved and will reconnect on app startup.",
    failedConnectBackend: "Failed to connect backend.",
    couldNotConnectBackend: "Could not connect backend",
    failedRemoveBackend: "Failed to remove backend.",
    couldNotRemoveBackend: "Could not remove backend",
    viewEnvironment: "View environment",
    viewEnvironmentDescription: "Read threads, status, diffs, and configuration.",
    operateTasks: "Operate tasks",
    operateTasksDescription: "Start tasks and perform changes in the environment.",
    useTerminals: "Use terminals",
    useTerminalsDescription: "Create terminals and send input to running shells.",
    writeReviews: "Write reviews",
    writeReviewsDescription: "Create comments while reviewing changes.",
    viewAccess: "View access",
    viewAccessDescription: "Inspect pairing links and authorized clients.",
    manageAccess: "Manage access",
    manageAccessDescription: "Issue and revoke credentials for other clients.",
    viewRelay: "View relay",
    viewRelayDescription: "Inspect managed relay connectivity.",
    manageRelay: "Manage relay",
    manageRelayDescription: "Change managed tunnel connectivity.",
    accessWriteWarning: "This client can create or revoke access for other devices.",
    creating: "Creating…",
    hostedAppLinkCopied: "Hosted app link copied",
    pairingUrlCopied: "Pairing URL copied",
    pairingCodeCopied: "Pairing code copied",
    openHostedAppLink: "Open it in the browser on the device you want to connect.",
    openPairingUrl: "Open it in the client you want to pair to this environment.",
    pastePairingCode: "Paste it into another client to finish pairing.",
    couldNotCopyHostedAppLink: "Could not copy hosted app link",
    couldNotCopyPairingUrl: "Could not copy pairing URL",
    couldNotCopyPairingCode: "Could not copy pairing code",
    showingFullValue: "Showing the full value instead.",
    linkCreatedAt: "Link created at {time}",
    copyUnavailableHostedHint:
      "Clipboard copy is unavailable here. Open or manually copy this hosted app link on the device you want to connect.",
    copyUnavailablePairingHint:
      "Clipboard copy is unavailable here. Open or manually copy this full pairing URL on the device you want to connect.",
    setupRequired: "Setup required",
    default: "Default",
    disable: "Disable",
    setAsDefault: "Set as default",
    version: "Version",
    download: "Download",
    install: "Install",
    checkingForUpdates: "Checking…",
    downloadingUpdate: "Downloading…",
    upToDate: "Up to Date",
    checkForUpdates: "Check for Updates",
    updateAvailableDescription: "Update available.",
    currentVersionDescription: "Current version of the application.",
    updateTrack: "Update track",
    updateTrackDescription:
      "Stable follows full releases. Nightly follows the nightly desktop channel and can switch back to stable immediately.",
    hostedUpdateTrackDescription: "Switches the hosted app release channel.",
    stable: "Stable",
    nightly: "Nightly",
    latest: "Latest",
    couldNotChangeUpdateTrack: "Could not change update track",
    updateTrackChangeFailed: "Update track change failed.",
    couldNotDownloadUpdate: "Could not download update",
    downloadFailed: "Download failed.",
    couldNotInstallUpdate: "Could not install update",
    installFailed: "Install failed.",
    couldNotCheckUpdates: "Could not check for updates",
    automaticUpdatesUnavailable: "Automatic updates are not available in this build.",
    updateCheckFailed: "Update check failed.",
    startFromOrigin: "Start from origin",
    startFromOriginDescription:
      "Creates the worktree from the latest matching branch on origin instead of your local branch.",
    newWorktreesStartFromOrigin: "new worktrees start from origin",
    startNewWorktreesFromOrigin: "Start new worktrees from origin by default",
    addProjectStartsIn: "Add project starts in",
    addProjectBaseDirectoryDescription:
      'Leave empty to use "~/" when the Add Project browser opens.',
    addProjectBaseDirectory: "add project base directory",
    textGenerationModel: "Text generation model",
    textGenerationModelDescription:
      "Configure the model used for generated commit messages, PR titles, and similar Git text.",
    about: "About",
    diagnostics: "Diagnostics",
    viewDiagnostics: "View diagnostics",
    unarchive: "Unarchive",
    delete: "Delete",
    failedUnarchiveThread: "Failed to unarchive thread",
    failedDeleteThread: "Failed to delete thread",
    archivedThreads: "Archived threads",
    loadingArchivedThreads: "Loading archived threads",
    couldNotLoadArchivedThreads: "Could not load archived threads",
    noArchivedThreads: "No archived threads",
    checkingConnectedEnvironments: "Checking connected environments.",
    archivedThreadsEmpty: "Archived threads will appear here.",
    archivedThreadActionFailed: "Archived thread action failed",
    archivedAt: "Archived {time}",
    createdAt: "Created {time}",
    browserDeviceToolbar: "Browser device toolbar",
    dimensions: "Dimensions",
    browserDevicePreset: "Browser device preset",
    responsive: "Responsive",
    standard: "Standard",
    viewportDimensions: "Viewport dimensions",
    viewportWidth: "Viewport width",
    viewportHeight: "Viewport height",
    lockViewportRatio: "Lock viewport aspect ratio",
    unlockViewportRatio: "Unlock viewport aspect ratio",
    lockRatio: "Lock aspect ratio",
    unlockRatio: "Unlock aspect ratio",
    rotateViewport: "Rotate viewport",
    closeDeviceToolbar: "Close device toolbar",
    moreComposerControls: "More composer controls",
    mode: "Mode",
    chat: "Chat",
    access: "Access",
    supervised: "Supervised",
    autoAcceptEdits: "Auto-accept edits",
    fullAccess: "Full access",
    favorites: "Favorites",
    disabledInSettings: "Disabled in settings.",
    unavailable: "Unavailable",
    limited: "Limited",
    notReady: "Not ready",
    new: "New",
    noPreviewYet: "No preview yet",
    noPreviewDescription:
      "Type a URL above, or run a dev script. Listening localhost ports will show up here automatically.",
    localServers: "Local servers",
    openListeningPort: "Select a listening port to open it in this browser tab.",
    listening: "Listening",
    configured: "Configured",
    recentlySeen: "Recently seen",
    notListening: "Not currently listening",
    previewMenu: "Preview menu",
    more: "More",
    hardReload: "Hard reload",
    openDevTools: "Open DevTools",
    hideDeviceToolbar: "Hide device toolbar",
    showDeviceToolbar: "Show device toolbar",
    zoom: "Zoom",
    zoomOut: "Zoom out",
    zoomIn: "Zoom in",
    resetZoom: "Reset zoom",
    clearCookies: "Clear cookies",
    clearCache: "Clear cache",
    checkoutFeatureAndContinue: "Check out feature branch & continue",
  },
  "zh-CN": {
    search: "搜索",
    projects: "项目",
    addProject: "添加项目",
    newThread: "新建线程",
    groupedProjects: "个项目",
    sidebarOptions: "侧栏选项",
    sortProjects: "项目排序",
    sortThreads: "线程排序",
    visibleThreads: "显示的线程",
    visibleThreadCount: "显示的线程数量",
    decreaseVisibleThreadCount: "减少显示的线程数量",
    increaseVisibleThreadCount: "增加显示的线程数量",
    groupProjects: "项目分组",
    sendMessage: "发送消息",
    plan: "规划",
    build: "构建",
    runtimeMode: "运行模式",
    hideSidebar: "隐藏{label}侧栏",
    showSidebar: "显示{label}侧栏",
    planModeHint: "规划模式 — 点击返回常规构建模式",
    buildModeHint: "默认模式 — 点击进入规划模式",
    resolveApproval: "请先处理此批准请求再继续",
    writeCustomAnswer: "填写自定义回答",
    expandComposer: "展开编辑器",
    typeOwnAnswer: "输入自定义回答，或留空以使用所选选项",
    refinePlan: "添加反馈以完善计划，或留空以执行计划",
    followUpOrAttach: "询问后续修改，或附加图片",
    composerPlaceholder: "输入任何内容，@ 标记文件或文件夹，$ 使用技能，/ 打开命令",
    attachAfterPlan: "请先回答规划问题，再附加图片。",
    unsupportedImage: "不支持“{name}”的文件类型，请仅附加图片文件。",
    imageTooLarge: "“{name}”超过了 {limit} 的附件大小限制。",
    tooManyImages: "每条消息最多可附加 {count} 张图片。",
    somethingWentWrong: "出现了一些问题。",
    tryAgain: "重试",
    reloadApp: "重新加载应用",
    showErrorDetails: "显示错误详情",
    hideErrorDetails: "隐藏错误详情",
    commandPalette: "命令面板",
    back: "返回",
    continue: "继续",
    working: "处理中",
    cloning: "正在克隆",
    repository: "仓库",
    navigate: "导航",
    select: "选择",
    close: "关闭",
    openIn: "在{name}中打开",
    newThreadIn: "在项目中新建线程…",
    newThreadInProject: "在 {project} 中新建线程",
    openWslFolder: "打开 WSL 文件夹",
    openSettings: "打开设置",
    unableToBrowseProjects: "无法浏览项目",
    noEnvironmentAvailable: "没有可用的环境。",
    enterGitUrl: "输入 Git 克隆 URL，然后按 Enter 继续。",
    enterRepositoryPath: "输入仓库路径，然后按 Enter 查找。",
    chooseCloneDestination: "选择目标路径，然后按 Enter 克隆。",
    relativePathNeedsProject: "相对路径需要当前项目。",
    createFolderAndAddProject: "按 Enter 创建此文件夹并将其添加为项目。",
    searchCommandsProjectsThreads: "搜索命令、项目和线程…",
    enterProjectPath: "输入项目路径（如 ~/projects/my-app）",
    searchPlaceholder: "搜索…",
    enterPath: "输入路径（如 ~/projects/my-app）",
    selectCloneDestination: "选择克隆目标位置",
    createAndClone: "创建并克隆",
    clone: "克隆",
    createAndAdd: "创建并添加",
    add: "添加",
    lookup: "查找",
    submitting: "正在提交…",
    submit: "提交",
    next: "下一步",
    nextQuestion: "下一题",
    submitAnswers: "提交回答",
    submitAnswer: "提交回答",
    previousQuestion: "上一题",
    previous: "上一步",
    stopGeneration: "停止生成",
    sending: "正在发送…",
    refine: "完善计划",
    implement: "执行",
    implementationActions: "执行操作",
    implementInNewThread: "在新线程中执行",
    environmentDisconnected: "环境已断开连接",
    connecting: "正在连接",
    preparingWorktreeShort: "正在准备工作树",
    cancelTurn: "取消本轮操作",
    decline: "拒绝",
    alwaysAllowSession: "始终允许此会话",
    approveOnce: "仅允许一次",
    removeReviewComment: "移除 {label} 上的评论",
    noActiveThread: "没有活动线程",
    pickThread: "选择一个线程以继续",
    pickThreadDescription: "选择已有线程，或新建一个线程以开始工作。",
    planActions: "计划操作",
    copied: "已复制！",
    copyToClipboard: "复制到剪贴板",
    downloadMarkdown: "下载 Markdown",
    saveToWorkspace: "保存到工作区",
    planSaved: "计划已保存",
    couldNotSavePlan: "无法保存计划",
    unexpectedError: "发生意外错误。",
    steps: "步骤",
    fullPlan: "完整计划",
    browser: "浏览器",
    terminal: "终端",
    files: "文件",
    diff: "差异",
    openSurface: "打开一个面板",
    chooseRightPanel: "选择要在右侧面板中显示的内容。",
    openLocalApp: "打开本地应用或 URL。",
    startShell: "在此工作区中启动 shell。",
    browseWorkspaceFiles: "浏览和阅读工作区文件。",
    reviewThreadChanges: "审查此线程中的变更。",
    browserDesktopOnly: "浏览器预览仅在 T3 Code 桌面应用中可用。",
    filesNeedProject: "打开项目后才能使用文件面板。",
    diffNeedsGit: "只有 Git 仓库中的服务端线程才能查看差异。",
    copyPath: "复制路径",
    closeOthers: "关闭其他面板",
    closeToRight: "关闭右侧面板",
    closeAll: "关闭全部面板",
    closeSurface: "关闭 {title}",
    addPanelSurface: "添加面板",
    indexing: "正在索引…",
    fileCount: "{count} 个文件",
    partial: "部分内容",
    searchWorkspaceFiles: "搜索工作区文件",
    refreshWorkspaceFiles: "刷新工作区文件",
    projectFiles: "{project} 的文件",
    unableOpenFileBrowser: "无法在浏览器中打开文件",
    showMarkdownSource: "显示 Markdown 源码",
    showRenderedMarkdown: "显示渲染后的 Markdown",
    openFilePreview: "在预览浏览器中打开文件",
    hideFileExplorer: "隐藏文件浏览器",
    showFileExplorer: "显示文件浏览器",
    previewLimited: "预览仅显示该 {count} 字节文件的前 1 MB。",
    publishRepository: "发布仓库…",
    detachedHeadWarning: "当前为分离 HEAD：请创建并检出分支以启用推送和拉取请求操作。",
    behindUpstreamWarning: "落后于上游，请先拉取或变基。",
    gitActions: "Git 操作",
    gitActionOptions: "Git 操作选项",
    branch: "分支",
    detachedHead: "（分离 HEAD）",
    defaultBranchWarning: "警告：默认分支",
    filesSelected: "（已选 {selected} / {total}）",
    done: "完成",
    edit: "编辑",
    none: "无",
    excluded: "已排除",
    commitMessageOptional: "提交说明（可选）",
    autoGenerateCommitMessage: "留空以自动生成",
    commitOnNewBranch: "提交到新分支",
    commit: "提交",
    runOnDefaultBranch: "要在默认分支上执行操作吗？",
    abort: "中止",
    cancel: "取消",
    timeFormat: "时间格式",
    systemClockPreference: "系统默认值遵循浏览器或操作系统的时钟偏好。",
    wordWrap: "自动换行",
    wordWrapDescription: "默认在代码块、表格、差异和文件预览中换行显示长文本。",
    hideWhitespaceChanges: "隐藏空白变更",
    hideWhitespaceDescription: "设置差异面板是否默认忽略仅空白字符的修改。",
    assistantOutput: "助手输出",
    assistantOutputDescription: "回复进行时逐 token 显示助手输出。",
    providerUpdateChecks: "提供商更新检查",
    providerUpdateDescription: "检查已安装的提供商 CLI 是否有可用的新版本。",
    autoOpenTaskPanel: "自动打开任务面板",
    autoOpenTaskDescription: "出现步骤时自动打开右侧的计划和任务面板。",
    newThreads: "新建线程",
    newThreadsDescription: "选择新建草稿线程的默认工作区模式。",
    local: "本地",
    newWorktree: "新建工作树",
    archiveConfirmation: "归档确认",
    archiveConfirmationDescription: "归档线程前，要求再次点击行内归档操作。",
    deleteConfirmation: "删除确认",
    deleteConfirmationDescription: "删除线程及其聊天记录前请求确认。",
    keybindings: "快捷键",
    bindingCount: "{count} 个快捷键",
    addKeybinding: "添加快捷键",
    openKeybindingsFile: "打开 keybindings.json",
    browserShortcutWarning:
      "部分快捷键可能会在 T3 Code 收到前被浏览器占用。使用桌面应用可获得更好的快捷键支持。",
    command: "命令",
    keybinding: "快捷键",
    when: "条件",
    status: "状态",
    noMatchingKeybindings: "没有与搜索内容匹配的快捷键。",
    liveProcesses: "运行中的进程",
    refreshProcessDiagnostics: "刷新进程诊断",
    childProcesses: "子进程",
    memory: "内存",
    serverPid: "服务器 PID",
    loadingLiveProcesses: "正在加载运行中的进程…",
    noLiveProcesses: "未找到正在运行的后代进程。",
    resourceHistory: "资源历史",
    refreshResourceHistory: "刷新资源历史",
    collectingResourceSamples: "正在收集进程资源采样…",
    noResourceSamples: "此时间窗口内没有进程资源采样。",
    traceDiagnostics: "追踪诊断",
    openLogsFolder: "打开日志文件夹",
    refreshTraceDiagnostics: "刷新追踪诊断",
    failures: "失败",
    slowSpans: "慢跨度",
    parseErrors: "解析错误",
    workingTree: "工作树",
    branchChanges: "分支变更",
    latestTurn: "最近一轮",
    searchRefs: "搜索引用…",
    stackedDiff: "堆叠差异视图",
    splitDiff: "拆分差异视图",
    disableLineWrapping: "关闭自动换行",
    enableLineWrapping: "开启自动换行",
    showWhitespaceChanges: "显示空白变更",
    loadingDiff: "正在加载差异…",
    noNetChanges: "此选择中没有净变更。",
    noPatchAvailable: "此选择没有可用补丁。",
    expandDiff: "展开差异",
    collapseDiff: "折叠差异",
    navigation: "导航",
    browserBack: "后退",
    forward: "前进",
    refresh: "刷新",
    stop: "停止",
    searchOrEnterUrl: "搜索或输入 URL",
    openInSystemBrowser: "在系统浏览器中打开",
    cancelAnnotation: "取消标注",
    cancelAnnotationShortcut: "取消标注（Esc）",
    annotatePreview: "标注预览",
    annotateElements: "标注元素、区域和绘图",
    stopRecording: "停止录制",
    captureScreenshot: "截取屏幕截图",
    screenshotOrRecord: "截图 · 按住 Shift 单击以录制",
    siteUnreachable: "无法访问此网站",
    previewConnectionIssue: "{host}：{reason}。",
    try: "请尝试：",
    checkConnection: "检查网络连接",
    confirmDevServer: "确认开发服务器正在运行",
    checkProxyFirewall: "检查代理和防火墙",
    details: "详细信息",
    hideDetails: "隐藏详细信息",
    reload: "重新加载",
    noTerminalSessions: "此线程还没有终端会话。",
    newTerminal: "新建终端",
    closeTerminal: "关闭终端",
    splitTerminalHorizontally: "水平拆分终端",
    splitTerminalVertically: "垂直拆分终端",
    terminalSplitLimit: "{action}（每组最多 {count} 个）",
    terminalWithShortcut: "{action}（{shortcut}）",
    terminalGroup: "组 {count}",
    projectScripts: "项目脚本",
    runAction: "运行 {name}",
    scriptActions: "脚本操作",
    addAction: "添加操作",
    editAction: "编辑 {name}",
    editActionTitle: "编辑操作",
    addActionTitle: "添加操作",
    actionsDescription: "操作是项目级命令，可从顶部工具栏或通过快捷键运行。",
    name: "名称",
    chooseIcon: "选择图标",
    pressShortcut: "按下快捷键",
    pressShortcutHelp: "按下一个快捷键。按 Backspace 清除。",
    previewUrlOptional: "预览 URL（可选）",
    openPreviewWhenRun: "此操作运行时，在应用内预览中打开此 URL。",
    runOnWorktreeCreate: "创建工作树时自动运行",
    autoOpenPreview: "运行此操作时自动打开预览",
    saveChanges: "保存更改",
    saveAction: "保存操作",
    deleteAction: "删除操作",
    deleteActionConfirm: "要删除操作“{name}”吗？",
    cannotUndo: "此操作无法撤销。",
    nameRequired: "名称不能为空。",
    commandRequired: "命令不能为空。",
    failedToSaveAction: "无法保存操作。",
    openInEditor: "在编辑器中打开",
    open: "打开",
    openFileInPreferredEditor: "在首选编辑器中打开文件",
    chooseEditor: "选择编辑器",
    noInstalledEditors: "未找到已安装的编辑器",
    addProviderInstance: "添加提供商实例",
    providers: "提供商",
    refreshProviderStatus: "刷新提供商状态",
    providerSettings: "{name} 提供商设置",
    addProviderDescription: "配置额外的提供商实例，例如指向其他工作区的第二个 Codex 安装。",
    driver: "驱动程序",
    identity: "身份",
    config: "配置",
    step: "第 {count} 步",
    comingSoon: "即将推出",
    label: "标签",
    providerLabelHint: "显示在提供商列表中，可选。",
    instanceId: "实例 ID",
    instanceIdHint: "线程和会话使用的路由键。仅限字母、数字、“-”或“_”。",
    accentColor: "强调色",
    providerAccentColor: "提供商实例强调色",
    useAccent: "使用 {color} 强调色",
    clear: "清除",
    accentColorHint: "在选择器中显示的可选标记。",
    noProviderConfiguration: "此驱动程序没有必填配置。现在可以添加实例。",
    addInstance: "添加实例",
    models: "模型",
    modelsAvailable: "共 {count} 个可用模型。",
    enterModelSlug: "请输入模型标识。",
    modelBuiltIn: "该模型已内置。",
    modelSlugTooLong: "模型标识不得超过 {count} 个字符。",
    customModelExists: "该自定义模型已保存。",
    fastMode: "快速模式",
    thinking: "思考",
    reasoning: "推理",
    modelDetails: "{name} 的详情",
    hidden: "已隐藏",
    custom: "自定义",
    removeFromFavorites: "从收藏中移除 {name}",
    addToFavorites: "将 {name} 添加到收藏",
    moveUp: "上移 {name}",
    moveDown: "下移 {name}",
    showModel: "显示 {name}",
    hideModel: "隐藏 {name}",
    showInPicker: "在选择器中显示",
    hideFromPicker: "在选择器中隐藏",
    removeCustomModel: "移除自定义模型",
    removeModel: "移除 {name}",
    workspace: "工作区",
    currentWorktree: "当前工作树",
    currentCheckout: "当前检出",
    worktree: "工作树",
    localCheckout: "本地检出",
    runOn: "运行位置",
    checkoutReference: "检出{name}",
    checkoutReferenceDescription:
      "解析 {provider} {name}，然后在主仓库或专用工作树中创建草稿线程。",
    referenceInputHint: "粘贴{name} URL、检出命令，或输入 123 / #123。",
    referenceInputInvalid: "请使用{name} URL、检出命令、123 或 #123。",
    failedToPrepareThread: "无法准备{name}线程。",
    referencePlaceholder: "{name} URL、检出命令，或 #42",
    branchTo: "{head} 到 {base}",
    resolvingReference: "正在解析{name}…",
    preparingLocal: "正在准备本地…",
    preparingWorktree: "正在准备工作树…",
    worktreeLocation: "工作树：{path}",
    worktreeLocationBranch: "工作树：{path}（{branch}）",
    terminalProcessRunning: "终端进程正在运行",
    remote: "远程",
    toggleMainSidebar: "切换主侧栏",
    toggleMainSidebarShortcut: "切换主侧栏（{shortcut}）",
    deleteProviderInstance: "删除提供商实例 {id}",
    deleteInstance: "删除实例",
    authenticatedAs: "已认证为",
    email: "电子邮箱",
    updateAvailable: "有可用更新",
    updating: "正在更新",
    updateNow: "立即更新",
    updateManually: "或手动运行以下命令更新",
    copyUpdateCommand: "复制更新命令",
    copyCommand: "复制命令",
    toggleDetails: "切换 {name} 的详情",
    enableProvider: "启用 {name}",
    displayName: "显示名称",
    instanceLabel: "实例标签",
    displayNameHint: "显示在提供商列表中的可选标签。",
    providerAccentDescription: "用于在选择器栏和模型列表中区分此实例。",
    environmentVariables: "环境变量",
    addEnvironmentVariable: "添加环境变量",
    environmentVariablesHint: "添加变量以传递 API 密钥、基础 URL 或此实例专属的其他 CLI 设置。",
    variable: "变量",
    value: "值",
    sensitive: "敏感",
    options: "选项",
    environmentVariableName: "环境变量名称 {count}",
    environmentVariableValue: "环境变量值 {count}",
    storedSecretHint: "已存储的密钥 — 输入新值以替换",
    markEnvironmentVariableSensitive: "将环境变量 {name} 标记为敏感",
    removeEnvironmentVariable: "移除环境变量 {name}",
    sensitiveValueStorage: "敏感值会单独存储，保存后不会再返回给应用。",
    customHexAccentColor: "自定义十六进制强调色",
    chooseCustomAccentColor: "为 {name} 选择自定义强调色",
    clearAccentColor: "清除 {name} 的强调色",
    binaryPath: "二进制路径",
    binaryPathDescription: "此实例使用的提供商二进制文件路径。",
    homePath: "主目录路径",
    homePathDescription: "此实例的自定义主目录和配置目录。",
    shadowHomePath: "影子主目录路径",
    shadowHomePathDescription: "账户专用主目录：认证信息独立保存，同时共享配置状态。",
    launchArguments: "启动参数",
    launchArgumentsDescription: "会话启动时传入的额外 CLI 参数。",
    apiEndpoint: "API 端点",
    apiEndpointDescription: "覆盖此实例的 API 端点。",
    serverUrl: "服务器 URL",
    serverUrlDescription: "留空以让 T3 Code 在需要时启动服务器。",
    serverPassword: "服务器密码",
    serverPasswordDescription: "以明文形式存储在磁盘上。",
    toggleAccountEmailVisibility: "切换账号邮箱可见性",
    revealEmail: "点击显示邮箱",
    hideEmail: "点击隐藏邮箱",
    updateCommandCopied: "已复制 {name} 更新命令",
    updateCommandCopiedDescription: "准备更新时，请在终端中运行该命令。",
    couldNotCopyUpdateCommand: "无法复制 {name} 更新命令",
    instanceIdRequired: "必须填写实例 ID。",
    instanceIdTooLong: "实例 ID 最多为 64 个字符。",
    instanceIdInvalid: "实例 ID 必须以字母开头，且只能使用字母、数字、“-”或“_”。",
    instanceIdExists: "名为“{id}”的实例已存在。",
    providerInstanceAdded: "已添加提供商实例",
    providerInstanceAddedDescription: "已添加 {name} 实例“{id}”。",
    couldNotAddProviderInstance: "无法添加提供商实例",
    updateFailed: "更新失败。",
    checkingProviderStatus: "正在检查提供商状态",
    waitingProviderStatus: "正在等待服务器报告安装与认证详情。",
    disabled: "已禁用",
    providerDisabledDescription: "此提供商已安装，但已禁止用于 T3 Code 的新会话。",
    notFound: "未找到",
    cliNotDetected: "未在 PATH 中检测到 CLI。",
    authenticated: "已认证",
    authenticatedWithLabel: "已认证 · {label}",
    notAuthenticated: "未认证",
    needsAttention: "需要关注",
    providerWarningDescription: "提供商已安装，但服务器无法完全验证它。",
    providerUnavailableDescription: "提供商未通过启动检查。",
    available: "可用",
    providerAvailableDescription: "已安装并就绪，但无法验证认证状态。",
    updateAvailableVersion: "有可用更新：请安装 {version}。",
    updateAvailableLatest: "有可用更新：请安装最新提供商版本。",
    toggleTask: "切换任务",
    openInIntegratedBrowser: "在内置浏览器中打开",
    collapseTableCells: "折叠表格单元格",
    expandTableCells: "展开表格单元格",
    copyTable: "复制表格",
    copyAsMarkdown: "复制为 Markdown",
    copyAsCsv: "复制为 CSV",
    language: "语言：{language}",
    disableLineWrap: "关闭自动换行",
    wrapLines: "自动换行",
    copyCode: "复制代码",
    unableToOpenFile: "无法打开文件",
    unableToOpenFileInBrowser: "无法在浏览器中打开文件",
    errorOccurred: "发生错误。",
    failedToCopy: "无法复制{name}",
    clipboardUnavailable: "剪贴板 API 不可用。",
    copiedValue: "已复制{name}",
    copyRelativePath: "复制相对路径",
    copyFullPath: "复制完整路径",
    relativePath: "相对路径",
    fullPath: "完整路径",
    resetToDefault: "恢复默认值",
    resetSettingToDefault: "将{name}恢复为默认值",
    revoking: "正在撤销…",
    revokeOthers: "撤销其他设备",
    createLink: "创建链接",
    createPairingLink: "创建配对链接",
    pairingLinkDescription: "生成一个一次性链接，其他设备可使用它作为已授权客户端与此后端配对。",
    clientLabelOptional: "客户端标签（可选）",
    permissions: "权限",
    limitPairedClient: "限制已配对客户端可执行的操作。",
    readOnly: "只读",
    selectPermission: "请至少选择一项权限。",
    failedCreatePairingUrl: "创建配对 URL 失败。",
    couldNotCreatePairingUrl: "无法创建配对 URL",
    thisDevice: "此设备",
    clientScopes: "客户端权限范围",
    revoke: "撤销",
    host: "主机",
    pairingCode: "配对码",
    pastePairingUrlHint: "在此粘贴完整的配对 URL，即可自动填充两个字段。",
    addEnvironment: "添加环境",
    addingEnvironment: "正在添加…",
    sshHostOrAlias: "SSH 主机或别名",
    searchHostsOrType: "搜索主机或输入 devbox",
    username: "用户名",
    port: "端口",
    suggestedHosts: "建议的主机",
    suggestedHostsDescription: "来自 SSH 配置和已知主机",
    noNewSshHosts: "未发现新的 SSH 主机。",
    remoteEnvironments: "远程环境",
    addEnvironmentTitle: "添加环境",
    addEnvironmentDescription: "将另一个环境配对到此客户端。",
    remoteLink: "远程链接",
    remoteLinkDescription: "输入后端主机和配对码。",
    sshConnectionDescription: "使用本地 SSH 配置、代理和隧道连接后端。",
    pairingLink: "配对链接",
    pairingUrls: "配对 URL",
    hostedAppLink: "托管应用链接",
    tokenOnly: "仅令牌",
    showQrCode: "显示二维码",
    scanPairingLink: "配对链接 — 扫码后在另一台设备上打开",
    pairingLinkScopes: "配对链接权限范围",
    copyTokenPairingHint: "复制令牌后，使用此后端可访问的主机在另一客户端中完成配对。",
    copyPairingUrlFor: "复制用于 {endpoint} 的配对 URL",
    chooseEndpointToCopy: "选择要复制的端点",
    showLink: "显示链接",
    showCode: "显示代码",
    hostedAppPairingLink: "托管应用配对链接",
    pairingCodeTitle: "配对码",
    copyUnavailableCodeHint: "此处无法使用剪贴板复制。请手动将此代码复制到另一客户端。",
    scopeCountOne: "{count} 个权限范围",
    scopeCountOther: "{count} 个权限范围",
    connectedFor: "已连接 {duration}",
    connected: "已连接",
    lastConnectedAt: "上次连接于 {time}",
    notConnectedYet: "尚未连接。",
    traceIdCopied: "已复制追踪 ID",
    couldNotCopyTraceId: "无法复制追踪 ID",
    versionDrift: "版本不一致：客户端 {client}，服务器 {server}。",
    copyTraceId: "复制追踪 ID",
    managedAbove: "由上方设置管理",
    wslManagedHint: "WSL 后端由上方的 WSL 设置管理，请在那里将其开启或关闭。",
    disconnecting: "正在断开连接…",
    disconnect: "断开连接",
    connect: "连接",
    noSavedRemoteEnvironments: "没有已保存的远程环境",
    noSavedRemoteEnvironmentsCloud: "点击“添加环境”配对其他环境，或从 T3 Connect 连接一个环境。",
    noSavedRemoteEnvironmentsLocal: "点击“添加环境”配对其他环境。",
    hide: "隐藏",
    reachableAt: "可访问地址：",
    networkAccess: "网络访问",
    enableNetworkAccess: "启用网络访问",
    exposedOnAllInterfaces: "已暴露在所有网络接口上。",
    exposedOnAllInterfacesWithHost: "已暴露在所有网络接口上。配对链接使用 {host}。",
    limitedToThisMachine: "仅限此设备访问。",
    loading: "正在加载…",
    remoteAccessConfigured: "此后端已配置远程访问。网络暴露设置需要在启动服务器的位置更改。",
    localOnlyAccess: "此后端仅能在本机访问。请以非回环地址重启它，以启用远程配对。",
    tailscaleHttpsDescription: "使用 Tailscale Serve 通过 MagicDNS HTTPS URL 暴露此后端。",
    tailscaleStartDescription: "启动 Tailscale 以通过 MagicDNS 设置 HTTPS 访问。",
    enableTailscaleHttps: "启用 Tailscale HTTPS",
    enableNetworkAccessConfirm: "启用网络访问？",
    disableNetworkAccessConfirm: "禁用网络访问？",
    enableNetworkAccessDescription: "T3 Code 将重启，以便通过网络暴露此环境。",
    disableNetworkAccessDescription: "T3 Code 将重启，并把此环境重新限制为仅本机访问。",
    restarting: "正在重启…",
    restartAndEnable: "重启并启用",
    restartAndDisable: "重启并禁用",
    disableTailscaleHttpsConfirm: "禁用 Tailscale HTTPS？",
    disableTailscaleHttpsDescription: "T3 Code 将在未启用 Tailscale Serve 的情况下重启本地后端。",
    setupTailscaleHttpsConfirm: "设置 Tailscale HTTPS？",
    setupTailscaleHttpsDescription:
      "T3 Code 将启用 Tailscale Serve 并重启本地后端，同时请求 Tailscale 将 HTTPS 流量代理到此后端。",
    httpsPort: "HTTPS 端口",
    enterHttpsPortRange: "请输入 1 到 65535 之间的端口。",
    httpsEndpoint: "HTTPS 端点",
    pendingMagicDnsEndpoint: "等待 MagicDNS 端点",
    enable: "启用",
    wslBackend: "WSL 后端",
    couldNotLoadWslBackend: "无法加载 WSL 后端状态。",
    retrying: "正在重试…",
    retry: "重试",
    wslUnavailableDescription:
      "WSL 已不可用，因此正在运行 Windows 后端。关闭 WSL 后端即可清除此偏好设置。",
    switchToWindows: "切换到 Windows",
    off: "关闭",
    defaultDistro: "默认发行版",
    wslBackendDescription:
      "在 Windows 后端旁的 WSL 发行版中运行第二个后端。选择发行版以启动它，选择“关闭”以停止它。通过 WSL 后端打开的项目位于 Linux 侧，Windows 项目仍保留在原位置。",
    wslBackendStartFailed: "WSL 后端无法启动：{error}",
    defaultMarker: "（默认）",
    wslOnly: "仅使用 WSL",
    wslOnlyDescription:
      "停止 Windows 后端，仅运行 WSL 后端。适合完全在 WSL 中开发且不需要第二个后端进程的情况。更改时 T3 Code 会重启。",
    runWslOnly: "仅运行 WSL",
    turnOffWslAndSwitchWindows: "关闭 WSL 并切换回 Windows？",
    disableWslBackend: "禁用 WSL 后端？",
    switchWslDistro: "切换 WSL 发行版？",
    startWslBackend: "启动 WSL 后端",
    runOnlyWslBackend: "仅运行 WSL 后端？",
    reenableWindowsBackend: "重新启用 Windows 后端？",
    wslSwitchWindowsDescription:
      "T3 Code 将在 Windows 后端上重启。通过 WSL 打开的线程和项目会安全保留在该发行版中，并会在重新启用 WSL 后再次可用。",
    wslDisableDescription:
      "WSL 后端将停止。通过 WSL 打开的线程和项目会安全保留在该发行版中，但在重新启用 WSL 前无法在 T3 Code 中使用。",
    wslSwitchDistroDescription:
      "T3 Code 将在新的发行版上重启 WSL 后端。当前发行版中仍在运行的会话将被中断。",
    wslStartDescription:
      "可在 Windows 后端旁运行 WSL 后端，或停止 Windows 后端并仅使用 WSL。稍后可以在设置中更改此项。",
    wslOnlyDescriptionConfirm:
      "T3 Code 将重启并仅启动 WSL 后端。Windows 端的项目将无法访问，直到再次关闭此选项。",
    wslReenableWindowsDescription: "T3 Code 将重启，并在 WSL 旁重新启动 Windows 后端。",
    applying: "正在应用…",
    useOnlyWsl: "仅使用 WSL",
    runBothBackends: "运行两个后端",
    disableWsl: "禁用 WSL",
    switchDistro: "切换发行版",
    enableT3Connect: "启用 T3 Connect",
    signInT3Connect: "登录 T3 Connect 以管理此环境。",
    noT3ConnectPermission: "当前会话没有管理 T3 Connect 访问权限。",
    t3ConnectLinked: "已连接 T3 Connect",
    t3ConnectTunnelDisabled: "已禁用 T3 Connect 隧道",
    t3ConnectUnlinked: "已解除 T3 Connect 连接",
    t3ConnectAvailable: "此环境可通过 T3 Connect 访问。",
    t3ConnectTunnelRemoved: "已移除托管隧道，代理活动发布仍保持开启。",
    t3ConnectUnavailable: "此环境不再可通过 T3 Connect 访问。",
    agentActivityEnabled: "已启用代理活动发布",
    agentActivityDisabled: "已禁用代理活动发布",
    agentActivityEnabledDescription: "此环境会向移动端客户端发布代理活动。",
    agentActivityDisabledDescription: "此环境将停止发布代理活动。",
    t3ConnectAvailableDevices: "此环境可通过 T3 Connect 供您的其他设备访问。",
    t3ConnectMakeAvailable: "通过 T3 Connect 让您的其他设备可以访问此环境。",
    publishAgentActivity: "发布代理活动",
    publishAgentActivityDescription:
      "将此环境的活动发送到移动端客户端，用于推送通知和实时活动。无需 T3 Connect 隧道也可使用。",
    publishAgentActivityAria: "向移动端客户端发布代理活动",
    failedNetworkExposure: "更新网络暴露设置失败。",
    couldNotUpdateNetworkAccess: "无法更新网络访问设置",
    failedConfigureTailscale: "配置 Tailscale HTTPS 失败。",
    couldNotSetupTailscale: "无法设置 Tailscale HTTPS",
    failedDisableTailscale: "禁用 Tailscale HTTPS 失败。",
    couldNotDisableTailscale: "无法禁用 Tailscale HTTPS",
    failedRevokePairingLink: "撤销配对链接失败。",
    couldNotRevokePairingLink: "无法撤销配对链接",
    failedRevokeClientAccess: "撤销客户端访问权限失败。",
    couldNotRevokeClientAccess: "无法撤销客户端访问权限",
    revokedOtherClient: "已撤销 1 个其他客户端",
    revokedOtherClients: "已撤销 {count} 个客户端",
    revokedOtherClientsDescription: "其他已配对客户端重新连接前需要新的配对链接。",
    failedRevokeOtherClients: "撤销其他客户端失败。",
    couldNotRevokeOtherClients: "无法撤销其他客户端",
    environmentConnected: "环境已连接",
    environmentReconnected: "环境已重新连接",
    sshTunnelReady: "{name} 已通过 SSH 托管隧道就绪。",
    failedAddBackend: "添加后端失败。",
    couldNotAddBackend: "无法添加后端",
    backendAdded: "已添加后端",
    backendAddedDescription: "环境已保存，并会在应用启动时重新连接。",
    failedConnectBackend: "连接后端失败。",
    couldNotConnectBackend: "无法连接后端",
    failedRemoveBackend: "移除后端失败。",
    couldNotRemoveBackend: "无法移除后端",
    viewEnvironment: "查看环境",
    viewEnvironmentDescription: "读取线程、状态、差异和配置。",
    operateTasks: "操作任务",
    operateTasksDescription: "在此环境中启动任务并执行更改。",
    useTerminals: "使用终端",
    useTerminalsDescription: "创建终端并向运行中的 Shell 发送输入。",
    writeReviews: "撰写审阅",
    writeReviewsDescription: "在审阅更改时创建评论。",
    viewAccess: "查看访问权限",
    viewAccessDescription: "查看配对链接和已授权客户端。",
    manageAccess: "管理访问权限",
    manageAccessDescription: "为其他客户端签发和撤销凭据。",
    viewRelay: "查看中继",
    viewRelayDescription: "查看托管中继的连接情况。",
    manageRelay: "管理中继",
    manageRelayDescription: "更改托管隧道的连接状态。",
    accessWriteWarning: "此客户端可以为其他设备创建或撤销访问权限。",
    creating: "正在创建…",
    hostedAppLinkCopied: "已复制托管应用链接",
    pairingUrlCopied: "已复制配对 URL",
    pairingCodeCopied: "已复制配对码",
    openHostedAppLink: "请在要连接的设备上用浏览器打开它。",
    openPairingUrl: "请在要与此环境配对的客户端中打开它。",
    pastePairingCode: "将它粘贴到另一客户端以完成配对。",
    couldNotCopyHostedAppLink: "无法复制托管应用链接",
    couldNotCopyPairingUrl: "无法复制配对 URL",
    couldNotCopyPairingCode: "无法复制配对码",
    showingFullValue: "将改为显示完整值。",
    linkCreatedAt: "链接创建于 {time}",
    copyUnavailableHostedHint:
      "此处无法使用剪贴板复制。请在要连接的设备上打开或手动复制此托管应用链接。",
    copyUnavailablePairingHint:
      "此处无法使用剪贴板复制。请在要连接的设备上打开或手动复制完整配对 URL。",
    setupRequired: "需要设置",
    default: "默认",
    setup: "设置",
    disable: "禁用",
    setAsDefault: "设为默认",
    version: "版本",
    download: "下载",
    install: "安装",
    checkingForUpdates: "正在检查…",
    downloadingUpdate: "正在下载…",
    upToDate: "已是最新版本",
    checkForUpdates: "检查更新",
    updateAvailableDescription: "有可用更新。",
    currentVersionDescription: "当前应用版本。",
    updateTrack: "更新通道",
    updateTrackDescription:
      "稳定版跟随完整正式发布；夜间版跟随桌面端夜间通道，并可立即切回稳定版。",
    hostedUpdateTrackDescription: "切换托管应用的发布通道。",
    stable: "稳定版",
    nightly: "夜间版",
    latest: "最新",
    couldNotChangeUpdateTrack: "无法更改更新通道",
    updateTrackChangeFailed: "更改更新通道失败。",
    couldNotDownloadUpdate: "无法下载更新",
    downloadFailed: "下载失败。",
    couldNotInstallUpdate: "无法安装更新",
    installFailed: "安装失败。",
    couldNotCheckUpdates: "无法检查更新",
    automaticUpdatesUnavailable: "此构建版本不支持自动更新。",
    updateCheckFailed: "检查更新失败。",
    startFromOrigin: "从 origin 开始",
    startFromOriginDescription: "从 origin 上最新的匹配分支创建工作树，而非从本地分支创建。",
    newWorktreesStartFromOrigin: "新工作树从 origin 开始",
    startNewWorktreesFromOrigin: "默认从 origin 创建新工作树",
    addProjectStartsIn: "添加项目的起始目录",
    addProjectBaseDirectoryDescription: "留空时，“添加项目”浏览器会从“~/”打开。",
    addProjectBaseDirectory: "添加项目的基础目录",
    textGenerationModel: "文本生成模型",
    textGenerationModelDescription: "配置用于生成提交消息、PR 标题和类似 Git 文本的模型。",
    about: "关于",
    diagnostics: "诊断",
    viewDiagnostics: "查看诊断信息",
    unarchive: "取消归档",
    delete: "删除",
    failedUnarchiveThread: "取消归档线程失败",
    failedDeleteThread: "删除线程失败",
    archivedThreads: "已归档线程",
    loadingArchivedThreads: "正在加载已归档线程",
    couldNotLoadArchivedThreads: "无法加载已归档线程",
    noArchivedThreads: "没有已归档线程",
    checkingConnectedEnvironments: "正在检查已连接环境。",
    archivedThreadsEmpty: "已归档线程会显示在这里。",
    archivedThreadActionFailed: "已归档线程操作失败",
    archivedAt: "归档于 {time}",
    createdAt: "创建于 {time}",
    browserDeviceToolbar: "浏览器设备工具栏",
    dimensions: "尺寸",
    browserDevicePreset: "浏览器设备预设",
    responsive: "响应式",
    standard: "标准",
    viewportDimensions: "视口尺寸",
    viewportWidth: "视口宽度",
    viewportHeight: "视口高度",
    lockViewportRatio: "锁定视口宽高比",
    unlockViewportRatio: "解除视口宽高比锁定",
    lockRatio: "锁定宽高比",
    unlockRatio: "解除宽高比锁定",
    rotateViewport: "旋转视口",
    closeDeviceToolbar: "关闭设备工具栏",
    moreComposerControls: "更多编辑器控制项",
    mode: "模式",
    chat: "对话",
    access: "访问权限",
    supervised: "需确认",
    autoAcceptEdits: "自动接受编辑",
    fullAccess: "完全访问",
    favorites: "收藏",
    disabledInSettings: "已在设置中禁用。",
    unavailable: "不可用",
    limited: "受限",
    notReady: "尚未就绪",
    new: "新",
    noPreviewYet: "暂无预览",
    noPreviewDescription:
      "在上方输入 URL，或运行开发脚本。正在监听的 localhost 端口会自动显示在这里。",
    localServers: "本地服务",
    openListeningPort: "选择一个正在监听的端口，以在此浏览器标签页中打开。",
    listening: "正在监听",
    configured: "已配置",
    recentlySeen: "最近访问",
    notListening: "当前未监听",
    previewMenu: "预览菜单",
    more: "更多",
    hardReload: "强制刷新",
    openDevTools: "打开开发者工具",
    hideDeviceToolbar: "隐藏设备工具栏",
    showDeviceToolbar: "显示设备工具栏",
    zoom: "缩放",
    zoomOut: "缩小",
    zoomIn: "放大",
    resetZoom: "重置缩放",
    clearCookies: "清除 Cookie",
    clearCache: "清除缓存",
    checkoutFeatureAndContinue: "检出功能分支并继续",
  },
} as const;

export type TranslationKey = keyof (typeof MESSAGES)["en"];

export function translate(
  language: Language,
  key: TranslationKey,
  values: Record<string, string | number> = {},
): string {
  return MESSAGES[language][key].replace(/\{(\w+)\}/g, (match, name: string) =>
    name in values ? String(values[name]) : match,
  );
}

const STORAGE_KEY = "t3code:language";
const DEFAULT_LANGUAGE: Language = "en";

let listeners: Array<() => void> = [];
let lastLanguage: Language | null = null;

function emitChange() {
  for (const listener of listeners) listener();
}

export function readLanguagePreference(): Language {
  if (typeof window === "undefined") return DEFAULT_LANGUAGE;
  const value = window.localStorage.getItem(STORAGE_KEY);
  return value === "zh-CN" || value === "en" ? value : DEFAULT_LANGUAGE;
}

export function writeLanguagePreference(language: Language): void {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(STORAGE_KEY, language);
}

export function isLanguage(value: unknown): value is Language {
  return typeof value === "string" && LANGUAGE_OPTIONS.some((option) => option === value);
}

export function applyLanguage(language: Language) {
  if (typeof document === "undefined") return;
  document.documentElement.lang = language;
}

function getSnapshot(): Language {
  const language = readLanguagePreference();
  if (lastLanguage === language) return lastLanguage;
  lastLanguage = language;
  return language;
}

function subscribe(listener: () => void): () => void {
  if (typeof window === "undefined") return () => {};
  listeners.push(listener);
  const handleStorage = (event: StorageEvent) => {
    if (event.key === STORAGE_KEY) emitChange();
  };
  window.addEventListener("storage", handleStorage);
  return () => {
    listeners = listeners.filter((candidate) => candidate !== listener);
    window.removeEventListener("storage", handleStorage);
  };
}

export function useLanguage() {
  const language = useSyncExternalStore(subscribe, getSnapshot, () => DEFAULT_LANGUAGE);

  useEffect(() => {
    applyLanguage(language);
  }, [language]);

  const setLanguage = useCallback((next: Language) => {
    writeLanguagePreference(next);
    applyLanguage(next);
    emitChange();
  }, []);

  return { language, setLanguage } as const;
}

export function useTranslation() {
  const { language, setLanguage } = useLanguage();
  const t = useCallback(
    (key: TranslationKey, values?: Record<string, string | number>) =>
      translate(language, key, values),
    [language],
  );

  return { language, setLanguage, t } as const;
}
